### ISSUE TITLE
Nullability support

### ISSUE THREAD

**Issue by dna-f** [escamoteur/rx_widgets#20]
Hi! 
Any plan to migrate this package after RXCommand?

**Comment by AlexBacich** [comment]
Created PR to this: https://github.com/escamoteur/rx_widgets/pull/21

**Comment by escamoteur** [comment]
Thanks a lot!
does this rely on your PR to rx_command?

**Comment by AlexBacich** [comment]
Not sure I understood you. I didn't make PR to rx_command - you have worked with other guy. I have waited when you released rx_command with nullability support and updates this one.

**Comment by escamoteur** [comment]
Oh, right, I mixed you up. I mean if I land this PR https://github.com/fluttercommunity/rx_command/pull/53
will it have an affect on you?

**Comment by escamoteur** [comment]
just pushed V4.0.0
