### ISSUE TITLE
RxCommandBuilder crashes if no busyBuilder, errorBuilder or placeholderBuilder builders.

### ISSUE THREAD

**Issue by RussellZornes** [escamoteur/rx_widgets#9]
```
  /// Creates a new `RxCommandBuilder` instance
  /// [commandResults] : `Stream<CommandResult<T>>` or a `RxCommand<T>` that issues `CommandResults`
  /// [busyBuilder] : Builder that will be called as soon as an event with `isExecuting==true`.
  /// [dataBuilder] : Builder that will be called as soon as an event with data is received. It will get passed the `data` feeld of the CommandResult.
  /// If this is null a `Container` will be created instead.
  /// [placeHolderBuilder] : Builder that will be called as soon as an event with `data==null` is received. 
  /// If this is null a `Container` will be created instead.
  /// [dataBuilder] : Builder that will be called as soon as an event with an `error` is received. It will get passed the `error` feeld of the CommandResult.
  /// If this is null a `Container` will be created instead.
```
Documentation:
The busyBuilder is not marked required but does not state what happens when null.
The last parameter should be [errorBuilder] not [dataBuilder].

Code:
The documentation for RxCommandBuilder says that a Container() will be created if builders are not provided however the code calls a null builders for busyBuilder, placeHolderBuilder and errorBuilder,

**Comment by escamoteur** [comment]
Hmm you are right that is against the documentation. I just wonder if its a good thing to just return a container because it might confuse the user because in this case nothing is displayed. Maybe it would be better to change the documentation instead?
What do you think?

**Comment by RussellZornes** [comment]
At this point it would be less disruptive to change the docs since I'm already dealing with it at the call sights. I'm good with updating the docs.

**Comment by AlexBacich** [comment]
My last commit addressed this issue es well.. Empty boxes are returned when builders not provided for error and placeholder, for missing busyBuilder progress indicator is rendered.

**Comment by AlexBacich** [comment]
@escamoteur , will you post update to pub.dev any time soon?

**Comment by escamoteur** [comment]
@AlexBacich could you write a small entry for the changelog please? You have a better overview what changed till the last version.

**Comment by AlexBacich** [comment]
@escamoteur , sorry for late response. 

New widgets: 
- Added RxCommandHandlerMixin.  It allows to listen for events from commands and yet remain widget Stateless
- Added ReactiveWidget. It's similar to ReactiveBuilder but without context in methods.

Existing widgets:
- WidgetSelector. Made onTrue, onFalse optional. Blank widget is used if null.
- RxCommandBuilder. Made possible to build with blank of Placeholder and Error. Blank widgets used in that case
Made possible to build with blank Busy. Also used platform parameter to build progress indicator if busy is null

**Comment by escamoteur** [comment]
NP

**Comment by escamoteur** [comment]
Just pushed V3.1.0 with the PR from @AlexBacich . Thanks a lot for this contribution
